name: touch_dispatch
description: TouchDispatch Flame game
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.22.0
  flame_bloc: ^1.12.12
  animated_flight_paths: ^0.0.3
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/plane.png
    - assets/images/plane_colored.png
    - assets/images/runway.png
